import { describe, it, expect, beforeAll } from 'vitest';
import { compressAssetsToWebP, updateAssetReferences, formatBytes, type CharxAssetLike } from './image-compressor';

// Test images generated by sharp (100×100 solid colors — large enough for WebP to be smaller)
let TEST_PNG: Buffer;
let TEST_JPEG: Buffer;

// SVG string as buffer (always skipped)
const TEST_SVG = Buffer.from(
  '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="red"/></svg>',
);

beforeAll(async () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const sharp = require('sharp');
  TEST_PNG = await sharp({
    create: { width: 100, height: 100, channels: 4, background: { r: 255, g: 0, b: 0, alpha: 1 } },
  })
    .png()
    .toBuffer();
  TEST_JPEG = await sharp({
    create: { width: 100, height: 100, channels: 3, background: { r: 0, g: 0, b: 255 } },
  })
    .jpeg({ quality: 90 })
    .toBuffer();
});

describe('compressAssetsToWebP', () => {
  it('converts PNG to WebP', async () => {
    const assets: CharxAssetLike[] = [{ path: 'assets/other/image/portrait.png', data: TEST_PNG }];
    const result = await compressAssetsToWebP(assets);

    expect(result.assets).toHaveLength(1);
    expect(result.assets[0].path).toBe('assets/other/image/portrait.webp');
    expect(result.details[0].status).toBe('converted');
    expect(result.stats.converted).toBe(1);
  });

  it('converts JPEG to WebP', async () => {
    const assets: CharxAssetLike[] = [{ path: 'assets/icon/char.jpg', data: TEST_JPEG }];
    const result = await compressAssetsToWebP(assets);

    expect(result.assets).toHaveLength(1);
    expect(result.assets[0].path).toBe('assets/icon/char.webp');
    expect(result.details[0].status).toBe('converted');
  });

  it('skips SVG files', async () => {
    const assets: CharxAssetLike[] = [{ path: 'assets/other/image/icon.svg', data: TEST_SVG }];
    const result = await compressAssetsToWebP(assets);

    expect(result.assets).toHaveLength(1);
    expect(result.assets[0].path).toBe('assets/other/image/icon.svg');
    expect(result.assets[0].data).toBe(TEST_SVG);
    expect(result.details[0].status).toBe('skipped');
    expect(result.details[0].reason).toContain('SVG');
    expect(result.stats.skipped).toBe(1);
  });

  it('skips already-WebP by default', async () => {
    // Create a tiny WebP from PNG first
    const preResult = await compressAssetsToWebP([{ path: 'assets/other/image/test.png', data: TEST_PNG }]);
    const webpAsset = preResult.assets[0];

    const result = await compressAssetsToWebP([webpAsset]);

    expect(result.details[0].status).toBe('skipped');
    expect(result.details[0].reason).toContain('Already WebP');
  });

  it('re-compresses WebP when recompressWebp is true', async () => {
    const preResult = await compressAssetsToWebP([{ path: 'assets/other/image/test.png', data: TEST_PNG }]);
    const webpAsset = preResult.assets[0];

    const result = await compressAssetsToWebP([webpAsset], {
      recompressWebp: true,
    });

    // Should attempt conversion (result depends on whether output is smaller)
    expect(['converted', 'larger']).toContain(result.details[0].status);
    expect(result.stats.skipped).toBe(0);
  });

  it('handles mixed assets', async () => {
    const assets: CharxAssetLike[] = [
      { path: 'assets/icon/face.png', data: TEST_PNG },
      { path: 'assets/other/image/bg.jpg', data: TEST_JPEG },
      { path: 'assets/other/image/logo.svg', data: TEST_SVG },
    ];
    const result = await compressAssetsToWebP(assets);

    expect(result.assets).toHaveLength(3);
    expect(result.stats.total).toBe(3);
    // PNG and JPEG should be converted, SVG skipped
    expect(result.stats.skipped).toBe(1);
    expect(result.stats.converted + result.stats.larger).toBe(2);
  });

  it('respects quality parameter', async () => {
    const assets: CharxAssetLike[] = [{ path: 'assets/icon/face.png', data: TEST_PNG }];
    const lowQ = await compressAssetsToWebP(assets, { quality: 10 });
    const highQ = await compressAssetsToWebP(assets, { quality: 100 });

    // Both should produce results
    expect(lowQ.stats.total).toBe(1);
    expect(highQ.stats.total).toBe(1);
  });

  it('computes correct stats', async () => {
    const assets: CharxAssetLike[] = [
      { path: 'assets/icon/a.png', data: TEST_PNG },
      { path: 'assets/icon/b.svg', data: TEST_SVG },
    ];
    const result = await compressAssetsToWebP(assets);

    expect(result.stats.total).toBe(2);
    expect(result.stats.originalSize).toBe(TEST_PNG.length + TEST_SVG.length);
    expect(result.stats.savedPercent).toBeGreaterThanOrEqual(0);
  });

  it('skips unsupported extensions', async () => {
    const assets: CharxAssetLike[] = [{ path: 'assets/other/data.json', data: Buffer.from('{}') }];
    const result = await compressAssetsToWebP(assets);

    expect(result.details[0].status).toBe('skipped');
    expect(result.details[0].reason).toContain('Unsupported');
  });
});

describe('updateAssetReferences', () => {
  it('updates cardAssets URI references', () => {
    const pathMap = new Map([['assets/icon/char.png', 'assets/icon/char.webp']]);
    const cardAssets: Record<string, unknown>[] = [
      { uri: 'ccdefault://assets/icon/char.png', name: 'char.png', ext: 'png' },
    ];
    const xMeta: Record<string, unknown> = {};

    const result = updateAssetReferences(pathMap, cardAssets, xMeta);

    expect(result.cardAssetsUpdated).toBe(1);
    expect(cardAssets[0].uri).toBe('ccdefault://assets/icon/char.webp');
    expect(cardAssets[0].ext).toBe('webp');
  });

  it('updates x_meta keys', () => {
    const pathMap = new Map([['assets/icon/portrait.png', 'assets/icon/portrait.webp']]);
    const cardAssets: Record<string, unknown>[] = [];
    const xMeta: Record<string, unknown> = { portrait: { type: 'PNG' } };

    const result = updateAssetReferences(pathMap, cardAssets, xMeta);

    // x_meta keys are based on filename without extension, so portrait → portrait (same key)
    // Only updates if the stem actually changes
    expect(result.xMetaUpdated).toBe(0);
    expect(xMeta['portrait']).toEqual({ type: 'PNG' });
  });
});

describe('formatBytes', () => {
  it('formats bytes correctly', () => {
    expect(formatBytes(500)).toBe('500 B');
    expect(formatBytes(1024)).toBe('1.0 KB');
    expect(formatBytes(1536)).toBe('1.5 KB');
    expect(formatBytes(1048576)).toBe('1.00 MB');
    expect(formatBytes(2621440)).toBe('2.50 MB');
  });
});
